packages:
  - 'apps/*'
  - 'packages/**'
  - 'resources/**'

catalog:
  '@radix-ui/react-icons': ^1.3.1
  '@types/react': 18.3.12
  '@types/react-dom': 18.3.1
  '@total-typescript/ts-reset': ^0.6.1
  drizzle-orm: ^0.37.0
  hono: ^4.6.10
  better-auth: 1.0.10
  dotenv-cli: ^7.4.2
  next: 15.0.3
  autoprefixer: ^10.4.20
  react: 19.0.0-rc-1631855f-20241023
  react-dom: 19.0.0-rc-1631855f-20241023
  react-hook-form: ^7.53.1
  postcss: ^8.4.47
  tailwindcss: ^3.4.14
  tailwind-merge: ^2.5.4
  tailwindcss-animate: ^1.0.7
  clsx: ^2.1.1
  lucide-react: ^0.454.0
  class-variance-authority: ^0.7.0
  zod: ^3.23.8
  superjson: ^2.2.1
  pg: ^8.13.1
