// @sts-nocheck
// This file is autogenerated by Valhalla
// Do not edit this file directly.
import * as React from 'react'

export const Components: Record<string, any> = {
  ImagePreview: {
    default: React.lazy(
      () => import('@valhalla/example/components/image-preview')
    ),
    name: 'ImagePreview',
  },
}
