// @sts-nocheck
// This file is autogenerated by Valhalla
// Do not edit this file directly.
import * as React from "react"

export const Icons: Record<string, any> = {
  YAML: {
    default: React.lazy(() =>
      import('@/components/icons').then((m) => ({
        default: () => <m.Icons.YAML />,
      }))
    ),
  },
  JSON: {
    default: React.lazy(() =>
      import('lucide-react').then((m) => ({
        default: () => <m.Braces />,
      }))
    ),
    name: 'JSON',
  },
  File: {
    default: React.lazy(() =>
      import('lucide-react').then((m) => ({
        default: () => <m.File />,
      }))
    ),
    name: 'File',
  },
}